#!/bin/bash

if ! [[ $1 ]]
then
    echo "Error: Backup name missing"
    echo "Please specify a backup name, e.g. 'restore 20141104'"
    echo "Finished: FAILURE"
    exit 1
fi

if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_PORT_3306_TCP_PORT" ]; then echo "Error: MYSQL_PORT_3306_TCP_PORT not set"; echo "Finished: FAILURE"; exit 1; fi

if ! [[ $1 =~ ^[a-zA-Z0-9_-]+$ ]]
then
  echo "The given backup name does not match the expected pattern: only characters, digits, underscore and dash are allowed ([a-zA-Z0-9_-])."
  echo 'Finished: FAILURE'
  exit 1
fi

CONFIG_BACKUP="/backups/config.ini.php.$1"
SQL_ARCHIVE="/backups/backup_$1.sql.bz2"

if [[ ! -f $CONFIG_BACKUP ]]
then
  echo "The file $CONFIG_BACKUP does not exist. Aborting."
  echo "Finished: FAILURE."
  exit 1
fi

if [[ ! -f $SQL_ARCHIVE ]]
then
  echo "The file $SQL_ARCHIVE does not exist. Aborting."
  echo "Finished: FAILURE."
  exit 1
fi


# cleanup old config 
echo "deleting file /var/www/html/config/config.ini.php"
rm -R /var/www/html/config/config.ini.php

# restore files
echo "restoring file $CONFIG_BACKUP to /var/www/html/config/config.ini.php"
cp $CONFIG_BACKUP /var/www/html/config/config.ini.php

# set correct file owner
chown www-data:www-data /var/www/html/config/config.ini.php

# restore database
echo "restoring data from mysql dump file $SQL_ARCHIVE"
bunzip2 < $SQL_ARCHIVE | mysql -u$MYSQL_ENV_MYSQL_USER -p $MYSQL_ENV_MYSQL_DATABASE -p$MYSQL_ENV_MYSQL_PASSWORD -h mysql 

echo 'Finished: SUCCESS'
